title: Boa noite Lorenzo
email: jonatasdp@gmail.com
description: >
  Olá eu sou o Jônatas Davi Paganini e sou o pai do Lorenzo.
  Quase toda noite conto uma história para ele antes de dormir.
  Então a algum tempo comecei a gravar as histórias.
  Então esse site concentra as gravações das histórias que conto pro meu filho antes de dormir.
  Os audios não tem cortes e nem são editados. São gravações espontâneas.
  Nossas histórias não tem limites, nem são patrocinadas. Tudo aqui é feito com muito amor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lorenzo.ideia.me" # the base hostname & protocol for your site
podcasts_url: "http://feeds.soundcloud.com/users/soundcloud:users:38203103/sounds.rss"
itunes_url: "https://itunes.apple.com/br/podcast/boa-noite-lorenzo/id1089365742?l=en"
twitter_username: jonatasdp
github_username:  jonatas

# Build settings
markdown: kramdown
gems:
  - jemoji
  - oembed
